### ISSUE TITLE
PLEASE DO NOT DO THAT THING AGAIN

### ISSUE THREAD

**Issue by abarnes278** [abarnes278/wolfer#1]
**IT IS ANNOYING AND IT DISTURBS ME.**

**Comment by iBuyMountainDew** [comment]
ok

**Comment by abarnes278** [comment]
Thank you. In the meantime, want to help me make my new web app?

**Note**: My web app uses Angular. If you are not familiar with Angular, you can look at the documentation [here](https://angular.io/docs).

**Comment by iBuyMountainDew** [comment]
Can you please close this issue, it's clogging up my feed.
